from __future__ import annotations

import shutil
import subprocess
import tempfile
from pathlib import Path
from typing import Any

from .paths import WorkPaths
from .utils import write_text


class LatexConfigError(ValueError):
    pass


def _latex(config: dict[str, Any]) -> dict[str, Any]:
    return config.get("latex", {})


def _tex_bool(value: Any, default: bool = False) -> bool:
    if value is None:
        return default
    return bool(value)


def validate_latex_config(config: dict[str, Any]) -> None:
    latex = _latex(config)
    engine = str(latex.get("engine", "xelatex")).lower()
    use_polyglossia = _tex_bool(latex.get("use_polyglossia"), engine == "xelatex")
    use_babel = _tex_bool(latex.get("use_babel"), False)
    if engine == "xelatex" and use_polyglossia and use_babel:
        raise LatexConfigError(
            "Invalid LaTeX config: xelatex cannot use both polyglossia and babel. "
            "Set latex.use_babel=false or latex.use_polyglossia=false."
        )


def _font_name(latex: dict[str, Any], key: str, default: str) -> str:
    return str(latex.get(key) or default).replace("\n", " ").strip()


def _language(latex: dict[str, Any]) -> str:
    return str(latex.get("main_language") or "russian")


def _other_languages(latex: dict[str, Any]) -> list[str]:
    langs = latex.get("other_languages", ["english"])
    if isinstance(langs, str):
        langs = [langs]
    return [str(lang) for lang in langs if str(lang).strip()]


def render_latex_header(config: dict[str, Any]) -> str:
    """Render the default Russian scientific XeLaTeX header.

    This header is generated from config instead of relying on Pandoc language
    variables, so XeLaTeX uses exactly one language system by default:
    polyglossia, not babel.
    """
    validate_latex_config(config)
    latex = _latex(config)
    engine = str(latex.get("engine", "xelatex")).lower()
    mainfont = _font_name(latex, "mainfont", "Times New Roman")
    sansfont = _font_name(latex, "sansfont", "Arial")
    monofont = _font_name(latex, "monofont", "Consolas")
    main_language = _language(latex)
    other_languages = _other_languages(latex)
    use_polyglossia = _tex_bool(latex.get("use_polyglossia"), engine == "xelatex")
    use_babel = _tex_bool(latex.get("use_babel"), False)
    use_unicode_math = _tex_bool(latex.get("use_unicode_math"), False)

    lines = [
        "% Generated by docx2xelatex: Russian XeLaTeX preset.",
        r"\usepackage{fontspec}",
        rf"\setmainfont{{{mainfont}}}",
        rf"\setsansfont{{{sansfont}}}",
        rf"\setmonofont{{{monofont}}}",
        "",
    ]
    if use_polyglossia:
        lines.extend(
            [
                r"\usepackage{polyglossia}",
                rf"\setmainlanguage{{{main_language}}}",
            ]
        )
        for lang in other_languages:
            lines.append(rf"\setotherlanguage{{{lang}}}")
        lines.extend(
            [
                "",
                rf"\newfontfamily\cyrillicfont{{{mainfont}}}[Script=Cyrillic]",
                rf"\newfontfamily\cyrillicfontsf{{{sansfont}}}[Script=Cyrillic]",
                rf"\newfontfamily\cyrillicfonttt{{{monofont}}}[Script=Cyrillic]",
                "",
            ]
        )
    elif use_babel:
        languages = ",".join([*other_languages, f"main={main_language}"])
        lines.extend([rf"\usepackage[{languages}]{{babel}}", ""])

    lines.extend(
        [
            r"\usepackage{amsmath}",
            r"\usepackage{amssymb}",
            r"\usepackage{mathtools}",
        ]
    )
    if use_unicode_math:
        lines.append(r"\usepackage{unicode-math}")
    lines.extend(
        [
            r"\usepackage{upgreek,tensor,xfrac}",
            r"\providecommand{\Uptheta}{\Theta}",
            r"\providecommand{\Upomega}{\Omega}",
            r"\providecommand{\Updelta}{\Delta}",
            r"\providecommand{\Upphi}{\Phi}",
            r"\providecommand{\Upsigma}{\Sigma}",
            r"\sloppy",
            "",
        ]
    )
    return "\n".join(lines)


def _write_header(workdir: Path, config: dict[str, Any]) -> Path:
    header = workdir / "header-xelatex-ru.tex"
    write_text(header, render_latex_header(config))
    return header


def _pandoc_latex_variables(config: dict[str, Any]) -> list[str]:
    latex = _latex(config)
    engine = str(latex.get("engine", "xelatex")).lower()
    use_polyglossia = _tex_bool(latex.get("use_polyglossia"), engine == "xelatex")
    variables = [
        f"documentclass={latex.get('documentclass', 'article')}",
        f"fontsize={latex.get('fontsize', '12pt')}",
    ]
    # With XeLaTeX+polyglossia, language and fonts are owned by the generated
    # header. Passing lang/mainfont/etc. through Pandoc can make Pandoc's
    # default template load babel or duplicate font setup.
    if not (engine == "xelatex" and use_polyglossia):
        variables.extend(
            [
                f"mainfont={latex.get('mainfont', 'Times New Roman')}",
                f"sansfont={latex.get('sansfont', 'Arial')}",
                f"monofont={latex.get('monofont', 'Consolas')}",
                f"lang={latex.get('lang', 'ru-RU')}",
            ]
        )
    return variables


def pandoc_final_to_tex(workdir: str | Path, config: dict[str, Any], force: bool = False) -> Path:
    validate_latex_config(config)
    wp = WorkPaths.from_workdir(workdir)
    wp.ensure()
    if wp.final_tex.exists() and not force:
        return wp.final_tex
    if not wp.final_md.exists():
        raise FileNotFoundError(f"final.md not found: {wp.final_md}")
    cmd = [
        "pandoc",
        str(wp.final_md),
        "-f",
        "markdown+raw_tex+tex_math_single_backslash",
        "-t",
        "latex",
        "--standalone",
        "-H",
        str(_write_header(wp.root, config)),
    ]
    for variable in _pandoc_latex_variables(config):
        cmd.extend(["-V", variable])
    cmd.extend(["--resource-path", str(wp.root), "-o", str(wp.final_tex)])
    proc = subprocess.run(cmd, text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    if proc.returncode != 0:
        raise RuntimeError(f"pandoc final build failed ({proc.returncode})\n{proc.stdout}\n{proc.stderr}")
    return wp.final_tex


def compile_tex(tex_path: str | Path, config: dict[str, Any], timeout: int = 240) -> dict[str, Any]:
    validate_latex_config(config)
    tex = Path(tex_path)
    latex = _latex(config)
    engine = str(latex.get("engine", "xelatex"))
    if shutil.which(engine) is None:
        return {"status": "failed", "pdf": None, "log": None, "error": f"{engine} not found"}
    args = [engine, "-interaction=nonstopmode"]
    if bool(latex.get("halt_on_error", False)):
        args.append("-halt-on-error")
    args.append(tex.name)
    last = None
    for _ in range(2):
        last = subprocess.run(args, cwd=tex.parent, text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=timeout)
        if last.returncode != 0 and latex.get("halt_on_error", False):
            break
    pdf = tex.with_suffix(".pdf")
    log = tex.with_suffix(".log")
    ok = pdf.exists() and last is not None and last.returncode == 0
    err = None if ok else ((last.stdout + "\n" + last.stderr)[-2000:] if last else "xelatex was not run")
    if not log.exists() and last:
        write_text(log, last.stdout + "\n" + last.stderr)
    return {"status": "ok" if ok else "failed", "pdf": str(pdf) if pdf.exists() else None, "log": str(log) if log.exists() else None, "error": err}


def compile_final_pdf(workdir: str | Path, config: dict[str, Any]) -> dict[str, Any]:
    wp = WorkPaths.from_workdir(workdir)
    latex = _latex(config)
    if not latex.get("build_pdf", True):
        return {"status": "skipped", "pdf": None, "log": None, "error": None}
    if not wp.final_tex.exists():
        raise FileNotFoundError(f"final.tex not found: {wp.final_tex}")
    return compile_tex(wp.final_tex, config)


def minimal_russian_latex_document(config: dict[str, Any]) -> str:
    latex = _latex(config)
    documentclass = latex.get("documentclass", "article")
    fontsize = latex.get("fontsize", "12pt")
    return "\n".join(
        [
            rf"\documentclass[{fontsize}]{{{documentclass}}}",
            render_latex_header(config),
            r"\begin{document}",
            "Тест русского текста.",
            r"\texttt{Тест моноширинного русского текста: АБВ абв ёЁ}",
            r"\[",
            r"a^2 + b^2 = c^2",
            r"\]",
            r"\end{document}",
            "",
        ]
    )


def run_latex_smoke_test(workdir: str | Path, config: dict[str, Any]) -> dict[str, Any]:
    validate_latex_config(config)
    wp = WorkPaths.from_workdir(workdir)
    wp.ensure()
    out_dir = wp.root / "latex-test"
    out_dir.mkdir(parents=True, exist_ok=True)
    tex = out_dir / "russian-xelatex-test.tex"
    write_text(tex, minimal_russian_latex_document(config))
    result = compile_tex(tex, config)
    return {"tex": str(tex), **result}


def _fc_match(font: str) -> dict[str, Any]:
    if shutil.which("fc-match") is None:
        return {"method": "fc-match", "available": False, "ok": None, "match": None}
    proc = subprocess.run(["fc-match", font], text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=10)
    out = proc.stdout.strip()
    return {"method": "fc-match", "available": True, "ok": proc.returncode == 0 and bool(out), "match": out or None, "error": proc.stderr.strip() or None}


def latex_doctor_checks(config: dict[str, Any]) -> dict[str, Any]:
    latex = _latex(config)
    engine = str(latex.get("engine", "xelatex"))
    report: dict[str, Any] = {
        "config_ok": True,
        "config_error": None,
        "engine": engine,
        "engine_path": shutil.which(engine),
        "engine_ok": shutil.which(engine) is not None,
        "use_polyglossia": _tex_bool(latex.get("use_polyglossia"), engine.lower() == "xelatex"),
        "use_babel": _tex_bool(latex.get("use_babel"), False),
        "use_unicode_math": _tex_bool(latex.get("use_unicode_math"), False),
        "fonts": {},
        "monofont_cyrillic_compile": None,
        "minimal_russian_compile": None,
    }
    try:
        validate_latex_config(config)
    except LatexConfigError as exc:
        report["config_ok"] = False
        report["config_error"] = str(exc)
        return report
    fonts = {
        "mainfont": _font_name(latex, "mainfont", "Times New Roman"),
        "sansfont": _font_name(latex, "sansfont", "Arial"),
        "monofont": _font_name(latex, "monofont", "Consolas"),
    }
    report["fonts"] = {key: {"name": value, **_fc_match(value)} for key, value in fonts.items()}
    if report["engine_ok"]:
        with tempfile.TemporaryDirectory(prefix="docx2xelatex-latex-doctor-") as tmp:
            smoke = run_latex_smoke_test(tmp, config)
            report["monofont_cyrillic_compile"] = smoke
            report["minimal_russian_compile"] = smoke
    return report


def build(workdir: str | Path, config: dict[str, Any], force: bool = False) -> dict[str, Any]:
    tex = pandoc_final_to_tex(workdir, config, force=force)
    pdf_result = compile_final_pdf(workdir, config)
    return {"tex": str(tex), **pdf_result}
